.PHONY : rosenbrock
rosenbrock :
	python plots.py \
	outdir/reset_4_rosenbrock_8d/ outdir/no_reset_rosenbrock_8d/ \
	--label reset_rosenbrock_8d \
	--run-labels "With reset" "Without reset" \
	--corner
